### ISSUE TITLE
Sign up Form Too Large

### ISSUE THREAD

**Issue by alexanderrudnik** [altence/lightence-ant-design-react-template#181]
**Is your feature request related to a problem? Please describe.**
Sign up form is too large and it's necessary to scroll it even on medium screens. Need to remove the scroll by updating the form.

**Describe the solution you'd like**
1. Remove `Confirm Password` input
2. Reduce space between form items
3. Place `Sign up with Google` and `Sign up with Facebook` on the same row.

**Comment by leineveber** [comment]
I disagree, TBD?
