### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by alexanderrudnik** [altence/lightence-ant-design-react-template#201]
**Describe the bug**
Once the user opens any page in dev mode, they see the following error: 

"
Warning: Using UNSAFE_componentWillMount in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.
Move code with side effects to componentDidMount, and set initial state in the constructor.

Please update the following components: SideEffect(NullComponent)
"

**Expected behavior**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/9514327/152792745-6ad50c57-dfee-4668-ab5e-8d2380865b9b.png)

**Comment by leineveber** [comment]
the errors comes from the package "react-helmet"

**Comment by leineveber** [comment]
Fixed in develop
