### ISSUE TITLE
Console Warning with z / z2 / zlevel

### ISSUE THREAD

**Issue by alexanderrudnik** [altence/lightence-ant-design-react-template#203]
**Describe the bug**
There is a console error once user opens any page

"
react_devtools_backend.js:4061 z / z2 / zlevel of displayable is invalid, which may cause unexpected errors
"

**Screenshots**
![image](https://user-images.githubusercontent.com/9514327/152795635-a2d8b014-d3bf-47cb-a92a-0696cf829ca4.png)

**Comment by leineveber** [comment]
can't reproduce
if you still have the warning please open new issue with steps to reproduce
