### ISSUE TITLE
Fix header profile button

### ISSUE THREAD

**Issue by Findmitrey** [altence/lightence-ant-design-react-template#227]
**Describe the bug**

When screen width is 1282px < width < 1362px the right "ProfileDropdown" move to next column. It's a reason why header have bigger height  and display search and button incorrectly.

**To Reproduce**
1. Go to 'Dashboard' page.
2. Resize screen to  1282px < width < 1362px
3. See that `search` input and `github` button shows incorrectly.

**Expected behavior**
`search` input and `github` button in header should display with correct styles. Header height should be the same on different screen sizes.

**Screenshots**
![Screenshot from 2022-08-10 12-04-55](https://user-images.githubusercontent.com/19979106/183861755-78a58f66-a3b8-4511-baae-69b26a5a9edf.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Google Chrome
 - Version 104.0.5112.79

**Comment by leineveber** [comment]
can't reproduce, everything works fine for me

**Comment by leineveber** [comment]
please check again, i remember that i fixed this issue half a year ago
