### ISSUE TITLE
Fix Ant Menu Deprecated Warnings

### ISSUE THREAD

**Issue by alexanderrudnik** [altence/lightence-ant-design-react-template#237]
**Is your feature request related to a problem? Please describe.**
Ant Design Menu component suggest to use `items` instead of `children` for better performace.

**Describe the solution you'd like**
Check sidebar and Dropdowns page and fix console warnings.

**Comment by UtkarshM-hub** [comment]
working on it

**Comment by leineveber** [comment]
Fixed in develop
