### ISSUE TITLE
Cannot build the project and deploy on Heroku (for example)

### ISSUE THREAD

**Issue by abdoulayefalltigo** [altence/lightence-ant-design-react-template#244]
Hello Team, thank you for this project !.
I forked this project to build my own app (it is for our office). I have almost finished the developments but i cannot deploy the app.
I cannot even see the "index.html" in the build folder (Looks like it have not been generated).

On heroku, the app is deployed but it cannot start. Here is what i got :

2022-11-17T11:30:11.611665+00:00 heroku[run.1263]: State changed from up to complete
2022-11-17T11:48:43.147702+00:00 heroku[web.1]: State changed from crashed to starting
2022-11-17T11:48:54.743785+00:00 heroku[web.1]: Starting process with command `npm start`
2022-11-17T11:48:56.457981+00:00 app[web.1]: 
2022-11-17T11:48:56.457996+00:00 app[web.1]: > kajou-store@1.0.0 start
2022-11-17T11:48:56.457997+00:00 app[web.1]: > yarn buildThemes && craco start
2022-11-17T11:48:56.457997+00:00 app[web.1]: 
2022-11-17T11:48:57.900755+00:00 app[web.1]: command not found: lessc
2022-11-17T11:48:58.054611+00:00 heroku[web.1]: Process exited with status 127
2022-11-17T11:48:58.119504+00:00 heroku[web.1]: State changed from starting to crashed

Please help me, i am almost at the deadline !!

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alexanderrudnik** [comment]
hello @abdoulayefalltigo 
thank you for submitting this.

the issue is on our side, I'll take a look

**Comment by alexanderrudnik** [comment]
@abdoulayefalltigo 
could you please provide your `package.json` file?

**Comment by abdoulayefalltigo** [comment]
@alexanderrudnik 

This is the content of package.json:

{
  "name": "kajou-store",
  "version": "1.0.0",
  "license": "MIT",
  "description": "La partie store de kajou !!",
  "repository": {
    "type": "git",
    "url": "https://github.com/kaj0u/kajou_store_front"
  },
  "bugs": {
    "url": "https://github.com/kaj0u/kajou_store_front"
  },
  "proxy": "http://localhost:3000",
  "homepage": "https://CarrickDev.github.io/kajou_store_front",
  "dependencies": {
    "@ant-design/icons": "^4.6.2",
    "@craco/craco": "^6.1.2",
    "@reduxjs/toolkit": "^1.7.1",
    "antd": "^4.22.4",
    "antd-mask-input": "^0.1.15",
    "axios": "^0.24.0",
    "axios-mock-adapter": "^1.20.0",
    "country-list": "^2.2.0",
    "dayjs": "^1.11.0",
    "echarts": "^5.1.2",
    "echarts-for-react": "^3.0.1",
    "elt-react-credit-cards": "^0.0.1",
    "google-map-react": "^2.1.10",
    "i18next": "^20.4.0",
    "leaflet": "^1.7.1",
    "patch-package": "^6.4.7",
    "pigeon-maps": "^0.19.7",
    "postinstall-postinstall": "^2.1.0",
    "react": "^17.0.2",
    "react-country-flag": "^3.0.2",
    "react-dom": "^17.0.2",
    "react-grid-layout": "^1.3.4",
    "react-helmet": "^6.1.0",
    "react-i18next": "^12.0.0",
    "react-infinite-scroll-component": "^6.1.0",
    "react-insta-stories": "^2.3.0",
    "react-leaflet": "next",
    "react-phone-number-input": "^3.1.27",
    "react-redux": "^7.2.6",
    "react-responsive": "^8.2.0",
    "react-router-dom": "^6.0.2",
    "react-router-hash-link": "^2.4.3",
    "react-scripts": "4.0.3",
    "react-select": "^5.6.0",
    "react-simple-maps": "^2.3.0",
    "react-slick": "^0.28.1",
    "react-trello": "^2.2.11",
    "react-verification-input": "^2.0.3",
    "slick-carousel": "^1.8.1",
    "styled-components": "^5.3.0",
    "typeface-lato": "^1.1.13",
    "typeface-montserrat": "^1.1.13",
    "typeface-poppins": "^1.1.13",
    "typescript": "^4.1.2",
    "uuid": "^8.3.2",
    "web-vitals": "^1.0.1",
    "workbox-background-sync": "^5.1.3",
    "workbox-broadcast-update": "^5.1.3",
    "workbox-cacheable-response": "^5.1.3",
    "workbox-core": "^5.1.3",
    "workbox-expiration": "^5.1.3",
    "workbox-google-analytics": "^5.1.3",
    "workbox-navigation-preload": "^5.1.3",
    "workbox-precaching": "^5.1.3",
    "workbox-range-requests": "^5.1.3",
    "workbox-routing": "^5.1.3",
    "workbox-strategies": "^5.1.3",
    "workbox-streams": "^5.1.3"
  },
  "scripts": {
    "start": "yarn buildThemes && craco start",
    "build": "yarn buildThemes && craco build",
    "test": "craco test",
    "eject": "craco eject",
    "lint": "eslint \"*/**/*.{js,ts,tsx}\" --fix",
    "lint:styles": "stylelint '*/**/*.{js,ts,tsx}'",
    "prepare": "husky install",
    "postinstall": "patch-package",
    "buildThemes": "lessc --js --clean-css=\"--s1 --advanced\" src/styles/themes/main.less public/themes/main.css"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not op_mini all",
    "not IE 11"
  ],
  "devDependencies": {
    "@types/country-list": "^2.1.0",
    "@types/google-map-react": "^2.1.3",
    "@types/leaflet": "^1.7.9",
    "@types/react": "^17.0.43",
    "@types/react-dom": "^17.0.14",
    "@types/react-helmet": "^6.1.5",
    "@types/react-phone-number-input": "^3.0.13",
    "@types/react-responsive": "^8.0.2",
    "@types/react-router-dom": "^5.1.7",
    "@types/react-router-hash-link": "^2.4.4",
    "@types/react-simple-maps": "^1.0.7",
    "@types/react-slick": "^0.23.8",
    "@types/styled-components": "^5.1.10",
    "@types/uuid": "^8.3.4",
    "@typescript-eslint/eslint-plugin": "^5.10.0",
    "@typescript-eslint/parser": "^5.8.0",
    "craco-alias": "^3.0.1",
    "eslint": "^7.28.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.0",
    "eslint-plugin-react": "^7.24.0",
    "eslint-plugin-react-hooks": "^4.3.0",
    "husky": "^6.0.0",
    "less": "^4.1.2",
    "less-plugin-clean-css": "^1.5.1",
    "lint-staged": "^11.0.0",
    "prettier": "^2.3.1",
    "stylelint": "^13.13.1",
    "stylelint-config-recommended": "^5.0.0",
    "stylelint-config-styled-components": "^0.1.1",
    "stylelint-processor-styled-components": "^1.10.0",
    "webpack-bundle-analyzer": "^4.4.2",
    "webpackbar": "^5.0.0-3"
  },
  "lint-staged": {
    "*/**/*.{js,ts,tsx}": "yarn lint"
  },
  "engines": {
    "node": "16.x"
  },
  "resolutions": {
    "react-error-overlay": "6.0.9"
  },
  "packageManager": "yarn@3.1.1",
  "keywords": [
    "lightence",
    "admin",
    "admin-dashboard",
    "ant-design",
    "react"
  ]
}

**Comment by alexanderrudnik** [comment]
@abdoulayefalltigo 
looks like heroku doesn't install devDependencies. Try to either move `"less": "^4.1.2",` from `devDependencies` into `dependencies` or set up heroku to install dev deps as well

**Comment by alexanderrudnik** [comment]
@abdoulayefalltigo 
any success?

**Comment by abdoulayefalltigo** [comment]
@alexanderrudnik sorry i was sick 🤒 the last two days. Unfortunately i haven’t found a solution with Heroku so i uploaded it through VERCEL and it works well. May be it is a problem with Heroku only.
Thank you very much !.
