### ISSUE TITLE
Broken scrolling and background in FireFox for starter project

### ISSUE THREAD

**Issue by Shultc** [altence/lightence-ant-design-react-template#251]
**Describe the bug**
When running starter project in FireFox custom scrolling of only content part is broken. Site works with default scroll behavior
![image](https://user-images.githubusercontent.com/458282/214905237-6c2df262-10fd-44af-982a-b872b6b0d628.png)

Also that brakes background filling. So full page looks like that:
![Screenshot 2023-01-26 at 19-20-56 Lightence Admin](https://user-images.githubusercontent.com/458282/214906277-af8159b5-b865-4069-bafa-6d92877c57a8.png)

No problem in Chrome.

Also, main project (from main branch) works as expected in FireFox.
![image](https://user-images.githubusercontent.com/458282/214906925-014e1c97-7534-4a8e-9c63-f7738003ef54.png)

**To Reproduce**
1. Create "starter" project by running `git clone -b starter https://github.com/altence/lightence-admin.git my-awesome-project && cd my-awesome-project`
2. Run it with `yarn install && yarn start`
3. Open http://localhost:3000/profile/personal-info in FireFox
4. Scroll to the bottom of the page

**Expected behavior**
Expected that starter project will work same as main one. Without broken styles.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser FireFox
 - Version 109.0

**Additional context**
It is really important for people who want to use this project as base for their project.

**Comment by leineveber** [comment]
Hello @Shultc, thank you for your issue.

We are sorry, but `starter` branch is now deprecated and soon will be deleted. Please, use `master` branch instead.

**Comment by Shultc** [comment]
Created Pull Request for removing this section from README.md
https://github.com/altence/lightence-ant-design-react-template/pull/254
