### ISSUE TITLE
Why do `main` and `v2.0.0` diverge?

### ISSUE THREAD

**Issue by nvmnghia** [altence/lightence-ant-design-react-template#253]
This is not a bug report, just a question. My code works in `main`, but not in `v2.0.0`, maybe due to some babel upgrade. After bisecting, I found out that `main` doesn't contain `v2.0.0` at all. Why is this the case? Which one should I use?

**Comment by leineveber** [comment]
What do you mean by `main` doesn't contain `2.0.0`? I see that main includes 2.0.0 by commits + a few more commits. 

Please use `main` branch if you have problems with `2.0.0`

**Comment by nvmnghia** [comment]
@leineveber this is the [v2][1] commit. Github says it's not contained in any branch.

  [1]: https://github.com/altence/lightence-ant-design-react-template/commit/54e7909e92dd2e98e44d002a8430924c4ec22b13

**Comment by leineveber** [comment]
@nvmnghia 
I see in `main` commits that its contained there

**Comment by nvmnghia** [comment]
Oh I see. Tip of [v2][1] and [main][2] are 2 different commits, though they may have the same content. Running

```bash
git log | grep $(git rev-list -n 1 tags/v2.0.0)
```
also yields nothing. Did you rebase the v2 on top of somewhere in main?

  [1]: https://github.com/altence/lightence-ant-design-react-template/commit/54e7909e92dd2e98e44d002a8430924c4ec22b13
  [2]: https://github.com/altence/lightence-ant-design-react-template/commit/0f88fe7221b909e004c279eec219fce8d5779de8

**Comment by leineveber** [comment]
@nvmnghia 
Just made a new release - 2.1.0. Please use it instead of 2.0.0
