### ISSUE TITLE
404. The page you are looking for doesn't exist or has been moved.

### ISSUE THREAD

**Issue by rushirufu** [altence/lightence-ant-design-react-template#268]
404. The page you are looking for doesn't exist or has been moved.

https://www.altence.com/lightence-admin-demo

**Comment by leineveber** [comment]
Hello @rushirufu,
Links are now updated, please try again. If you have any questions, feel free to open new issue

**Comment by rushirufu** [comment]
> Hello @rushirufu, Links are now updated, please try again. If you have any questions, feel free to open new issue

![image](https://user-images.githubusercontent.com/49694049/234708214-6f578f97-6226-4f5e-bbf1-81091eae7494.png)
