### ISSUE TITLE
error:03000086:digital envelope routines

### ISSUE THREAD

**Issue by No898** [altence/lightence-ant-design-react-template#272]
**Describe the bug**
when i try to start by "yarn start" it shows me "error:030000086: digital envelope routines::initialization error" ... more at screen.

**Expected behavior**
start server 

**Screenshots**
https://pasteboard.co/WSvFiLFumXWL.png

**Desktop (please complete the following information):**
Win11
 Chrome
 v. 113.0.5672.127 

node 20.0.0 (updated to 20.2, but nothing changed)

**Additional context**
I tried npm audit, reinstall and version you working on it at pull request, but nothing helps, on overstackflow people recommend only chance is downgrade node.

Thank you. Btw your your discord invite in readme doesnt work.

**Comment by pdkhanh3011** [comment]
try reclone and use node 16.13.0 it work for me

**Comment by No898** [comment]
Tried node 18.16 didnt work, downgrade again to 16. 20 and it works, thank you ban @pdkhanh3011

**Comment by Shubbu03** [comment]
hey!! i was also getting the same error but the following worked for me.. 

in your package.json file replace the existing start script with the following -> 
"start": "react-scripts --openssl-legacy-provider start"
it will work then

**Comment by Rozhkow** [comment]
Thank you for reaching out to us. We appreciate your interest in the Lightence platform.
At the moment, there are two ways to bypass this error:

1.Downgrade Node.js to version 16.
2.You can run the following command in your VS Code terminal: export NODE_OPTIONS=--openssl-legacy-provider. This command should help solve the error you encountered.
A global update will be released soon, addressing this issue. If you have any questions, feel free to ask, and we'll be happy to help
