### ISSUE TITLE
ANTD FormRef (ref) support, using the BaseButtonsForm Form?

### ISSUE THREAD

**Issue by adesheddie** [altence/lightence-ant-design-react-template#278]
**Is your feature request related to a problem? Please describe.**
There is a feature of ANTD Form, using which we can trigger Form events like submit, get validation errors anywhere we want, without having to use the actual submit button.

**Describe the solution you'd like**
I tried using the ref props, but it's not working on the BaseButtonsForm

**Comment by Rozhkow** [comment]
Thank you for reaching out to us. We appreciate your interest in the Lightence platform.
An update to our product will be released soon in which you will not encounter the problem with triggering form events, thank you.

If you have any remaining questions, we'll be happy to address them.
